"""Add ingredients column to pizzas table

Revision ID: 09163a42f986
Revises: e9c7b1579e98
Create Date: 2024-02-01 18:03:05.338971

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '09163a42f986'
down_revision = 'e9c7b1579e98'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('ingredients', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pizzas', schema=None) as batch_op:
        batch_op.drop_column('ingredients')

    # ### end Alembic commands ###
